---
name: Feature request
description: Suggest a new feature for the AdGuard Home Python client.
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any additional context, examples, or references.
    validations:
      required: false
